language: node_js
notifications:
  email: false
sudo: false
node_js:
  - '10'
env:
  - PACKAGE_NAME=eslint-config-redtn
  - PACKAGE_NAME=eslint-config-redtn-react
before_install:
  - npm install -g greenkeeper-lockfile
  - cd ./packages/$PACKAGE_NAME
install:
  - npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload